# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="mariadb-server-56-241-3307"
  config.vm.network "private_network", ip: "192.168.56.241"
  config.vm.network "forwarded_port", guest: 3306, host:3307
  config.vm.provider "virtualbox" do |vb|
     vb.name="mariadbServer"
     # vb.gui= true
     vb.memory = "1024"
     vb.cpus = 2
     vb.linked_clone = true
  end
  config.vm.synced_folder "./scripts", "/scripts"
  config.vm.provision "shell", path: "mariadb.sh"
end
 


