ENV["LC_ALL"] = "es_ES.UTF-8"
Vagrant.configure("2") do |config|
  config.vm.box = "techchad2022/ubuntu2204"
  config.vm.hostname='Ubu2204Cris'
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name='Ubuntu22.04-Vagrant'
    vb.gui = true
    end
  config.vm.synced_folder ".data", "/home/vagrant/data"
end
