# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname='Ubu2004es'
  #Rede HOST-ONLY 
  config.vm.network "private_network", ip: "192.168.33.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = 2
    vb.name='Ubuntu20.04-HostOnly'
    #vb.gui = true
    vb.check_guest_additions = false
    vb.linked_clone=true
  end
  config.vm.synced_folder "web", "/var/www/html"
  config.vm.provision "shell", inline: <<-SHELL
      echo "Iniciando actualización"
      apt-get update -y
      echo "Instalando paquetes idioma"
      apt-get install language-pack-es -y
      apt-get install language-pack-es-base -y
      echo "Modificando paquetes idioma"
      echo "LC_ALL=es_ES.UTF_8" >> /etc/default/locale
      echo "LANGUAGE=es_ES" >> /etc/default/locale
      echo "Modificando locale.gen"
      echo "es_ES.UTF-8 UTF-8" >> /etc/locale.gen
      locale-gen
      export LANG=es_ES.UTF-8
      apt-get install console-data -y
      apt-get install x11-xkb-utils -y
      setxkbmap -layout 'es,es' -model pc105
      sudo systemctl restart keyboard-setup.service
      echo "FIN"
      
      echo INSTALAMOS APACHE E CREAMOS UNHA PÁXINA
      apt-get update
      apt-get install -y apache2
      apt-get install -y php libapache2-mod-php php-mysql
      
      echo Reiniciamos apache
      sudo /etc/init.d/apache2 restart
      echo Acceemos ao directorio onde se publican paxinas web e creamos unha indes.html
      cd /var/www/html
      echo '<html><h2>O servidor Web funciona correctamente.</h2> <br><br>Benvido ao IES de Teis</html>' > index.html

  SHELL
end
