# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="mariadb-server-56-242-3308"
  config.vm.network "private_network", ip: "192.168.56.242"
  config.vm.network "forwarded_port", guest: 3306, host:3308
  config.vm.provider "virtualbox" do |vb|
     vb.name="mariadbServer"
     # vb.gui= true
     vb.memory = "1024"
     vb.cpus = 2
     vb.linked_clone = true
  end
  config.vm.synced_folder "./scripts", "/scripts"
  config.vm.provision "shell", inline: <<-SHELL
  echo "-----------------"

	echo "Actualizando"
	apt update -y
	echo "Asignando chave a BD"
	sudo echo "mariadb-server mariadb-server/root_password password renaido" | debconf-set-selections
	sudo echo "mariadb-server mariadb-server/root_password_again password renaido" | debconf-set-selections
	
	echo "Instalar mariadb"
	apt install mariadb-server -y
	echo "-----------------"
	
	echo "Parametros mysql-server"

	echo "Editando /etc/mysql/my.cnf "
	echo "[mysqld]" >> /etc/mysql/my.cnf 
	echo "character_set_server=utf8mb4" >> /etc/mysql/my.cnf 
	echo "collation_server=utf8mb4_unicode_ci" >> /etc/mysql/my.cnf 
	echo "bind-address = 0.0.0.0" >> /etc/mysql/my.cnf
	
	sudo systemctl start mariadb
	sudo systemctl enable mariadb

	echo " Dandolle acceso usuarsio DB "
	mysql -uroot -prenaido -h localhost -e "CREATE USER 'administrador'@'%' IDENTIFIED BY 'renaido'";
	mysql -uroot -prenaido -h localhost -e "GRANT ALL ON *.* TO 'administrador'@'%'";
	mysql -uroot -prenaido -h localhost -e "flush privileges";

	echo "Crear bd traballadores "
	mysql -uroot -prenaido -h localhost < /scripts/traballadores.sql
	echo "Crear bd tendaBD "
	mysql -uroot -prenaido -h localhost < /scripts/tendaBD.sql
	

	sudo systemctl restart mariadb
	
	echo "-----------------"
		
	echo "------ FIN ------"
  SHELL
end
 


