
Vagrant.configure("2") do |config|
  config.vm.box = "gusztavvargadr/ubuntu-desktop"
  config.vm.hostname = "ubuntuUsers"
  #Salvar error de descarga con certificado ssl
  config.vm.box_download_insecure = true

 
  config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
     vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
     vb.memory = "2048"
     vb.name="ubuntuUsuarios-vagrant"
  end
   config.vm.provision "shell", inline: <<-SHELL
      snap install flameshot
      apt install whois
      CONTRASINAL=$(mkpasswd -m sha-512 renaido) 
      useradd -b /home -m -p $CONTRASINAL admin 
   SHELL
end
