# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
#WEB
  config.vm.define "web01" do |web01|
    ## web01.vm.vbox = "ubuntu/focal64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.21", netmask: "255.255.255.0"
    web01.vm.network "forwarded_port", guest: 80, host: 8080
    web01.vm.network "forwarded_port", guest: 443, host: 4430
    web01.vm.synced_folder "./www", "/vagrant_www"
    web01.vm.provision "shell", path: "apache.sh" 
    web01.vm.provider "virtualbox" do |vb|
      vb.name = "web01"
      vb.memory = "1024"
      vb.cpus = 1
      vb.linked_clone = true
      vb.customize ["modifyvm", :id, "--groups", "/BDAPACHE"]
    end
  end
# DB
config.vm.define "mysql01" do |mysql01|
  ## mysql01.vm.box = "bento/ubuntu-16.04"
  mysql01.vm.hostname = "mysql01"
  mysql01.vm.network "private_network", ip: "192.168.56.22", netmask: "255.255.255.0"
  mysql01.vm.network "forwarded_port", guest: 3306, host: 3306
  mysql01.vm.provision "shell", path: "mysql.sh" 
  mysql01.vm.provider "virtualbox" do |vb|
    vb.name = "mysql01"
    vb.memory = "1024"
    vb.cpus = 2
    vb.linked_clone = true
    vb.customize ["modifyvm", :id, "--groups", "/BDAPACHE"]
  end
end
end
