# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname="web-lamp"
  config.vm.network "private_network", ip: "192.168.56.11"
  config.vm.network "forwarded_port", guest: 80, host:8080
  config.vm.network "forwarded_port", guest: 443, host:4430
  config.vm.network "forwarded_port", guest: 3306, host:3306
  config.vm.provider "virtualbox" do |vb|
     vb.name="web_lamp"
     vb.gui= true
     vb.memory = "1024"
     vb.cpus = 2
     vb.linked_clone = true
  end
  config.vm.synced_folder "./www", "/vagrant_www"
  config.vm.synced_folder "./scripts", "/scripts"
  config.vm.provision "shell", path: "lamp.sh"
end
